/*
 * Copyright (c) 2026. Janne Mareike Koschinski
 *
 * This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0.
 * If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
 */

package de.justjanne.voctotv.tv.ui.theme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF8E4F00)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFF8921E)
val onPrimaryContainerLight = Color(0xFF613400)
val secondaryLight = Color(0xFF2E627B)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFF497A95)
val onSecondaryContainerLight = Color(0xFFFCFCFC)
val tertiaryLight = Color(0xFF8B4C00)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFAF6100)
val onTertiaryContainerLight = Color(0xFFFFFBFF)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFF8F8F8)
val onBackgroundLight = Color(0xFF1A1A1A)
val surfaceLight = Color(0xFFF8F8F8)
val onSurfaceLight = Color(0xFF1B1B1B)
val surfaceVariantLight = Color(0xFFE3E3E3)
val onSurfaceVariantLight = Color(0xFF474747)
val outlineLight = Color(0xFF787878)
val outlineVariantLight = Color(0xFFC7C7C7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303030)
val inverseOnSurfaceLight = Color(0xFFF0F0F0)
val inversePrimaryLight = Color(0xFFFFB877)
val surfaceDimLight = Color(0xFFD9D9D9)
val surfaceBrightLight = Color(0xFFF8F8F8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF3F3F3)
val surfaceContainerLight = Color(0xFFEDEDED)
val surfaceContainerHighLight = Color(0xFFE7E7E7)
val surfaceContainerHighestLight = Color(0xFFE2E2E2)

val primaryDark = Color(0xFFFFB877)
val onPrimaryDark = Color(0xFF4C2700)
val primaryContainerDark = Color(0xFFF8921E)
val onPrimaryContainerDark = Color(0xFF613400)
val secondaryDark = Color(0xFF9CCDEA)
val onSecondaryDark = Color(0xFF003549)
val secondaryContainerDark = Color(0xFF6697B2)
val onSecondaryContainerDark = Color(0xFF002230)
val tertiaryDark = Color(0xFFFFB77A)
val onTertiaryDark = Color(0xFF4C2700)
val tertiaryContainerDark = Color(0xFFD37B1C)
val onTertiaryContainerDark = Color(0xFF402000)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF121212)
val onBackgroundDark = Color(0xFFDFDFDF)
val surfaceDark = Color(0xFF131313)
val onSurfaceDark = Color(0xFFE2E2E2)
val surfaceVariantDark = Color(0xFF474747)
val onSurfaceVariantDark = Color(0xFFC7C7C7)
val outlineDark = Color(0xFF919191)
val outlineVariantDark = Color(0xFF474747)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE2E2E2)
val inverseOnSurfaceDark = Color(0xFF303030)
val inversePrimaryDark = Color(0xFF8E4F00)
val surfaceDimDark = Color(0xFF131313)
val surfaceBrightDark = Color(0xFF393939)
val surfaceContainerLowestDark = Color(0xFF0E0E0E)
val surfaceContainerLowDark = Color(0xFF1B1B1B)
val surfaceContainerDark = Color(0xFF1F1F1F)
val surfaceContainerHighDark = Color(0xFF2A2A2A)
val surfaceContainerHighestDark = Color(0xFF343434)
